import path from 'node:path';
import type { CreatePlan } from '../types.js';
import { writeFileSafe } from '../utils/files.js';
import { toTitle } from '../utils/strings.js';
import { starterBranding } from './starterBranding.js';

export async function applyFullstackPlan(plan: CreatePlan): Promise<void> {
  if (plan.blueprint !== 'fullstack-product') {
    throw new Error(
      'applyFullstackPlan can only be used with fullstack-product plans.'
    );
  }

  await writeLayout(plan);
  await writeHomePage(plan);
  await writeDashboardPage(plan);
  await writeDashboardComponents(plan);
  await writeHealthRoute(plan);
  await writeServerFiles(plan);
  await writeLibFiles(plan);
  await writeTypesFile(plan);
}

async function writeLayout(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/app/layout.tsx'),
    `import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: ${JSON.stringify(toTitle(plan.projectName))},
  description: 'Generated full-stack product starter.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
`
  );
}

async function writeHomePage(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/app/page.tsx'),
    `import Link from 'next/link';
import { Sparkles, ArrowRight, LayoutDashboard, Activity } from 'lucide-react';

export default function HomePage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="border-b border-slate-200/80 bg-white/80 backdrop-blur-md sticky top-0 z-50">
        <div className="mx-auto max-w-6xl px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="h-6 w-6 rounded-lg bg-indigo-600 flex items-center justify-center text-xs font-bold text-white shadow-sm shadow-indigo-500/30">
              P
            </span>
            <span className="text-base font-bold tracking-tight text-slate-900">${toTitle(plan.projectName)}</span>
          </div>
          <Link href="/dashboard" className="text-sm font-semibold text-indigo-600 hover:text-indigo-500 transition inline-flex items-center gap-1">
            Go to Dashboard
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </header>

      <main className="flex-1 mx-auto max-w-4xl px-6 py-24 flex flex-col justify-center text-center relative overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 -z-10 h-72 w-72 rounded-full bg-indigo-400/10 blur-3xl pointer-events-none" />

        <div>
          <span className="inline-flex items-center gap-1.5 rounded-full bg-indigo-50 px-3.5 py-1.5 text-xs font-semibold text-indigo-700 ring-1 ring-inset ring-indigo-700/10">
            <Sparkles className="h-3.5 w-3.5 animate-pulse" />
            v1.3.0 • Premium Blueprint Starters
          </span>
          <h1 className="mt-8 text-4xl font-extrabold tracking-tight text-slate-900 sm:text-6xl bg-gradient-to-r from-indigo-600 via-violet-600 to-indigo-500 bg-clip-text text-transparent">
            ${toTitle(plan.projectName)}
          </h1>
          <p className="mt-6 text-lg leading-8 text-slate-600 max-w-2xl mx-auto font-medium">
            A premium full-stack SaaS platform generated by project-cli, pre-configured with server actions, API health polling, Docker deployment files, and database schemas.
          </p>
          <div className="mt-10 flex items-center justify-center gap-4">
            <Link
              href="/dashboard"
              className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-6 py-3.5 text-sm font-semibold text-white shadow-md shadow-indigo-500/20 hover:bg-indigo-500 transition duration-200"
            >
              <LayoutDashboard className="h-4 w-4" />
              Open Dashboard
            </Link>
            <Link
              href="/api/health"
              target="_blank"
              className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white/80 backdrop-blur-sm px-6 py-3.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 transition duration-200"
            >
              <Activity className="h-4 w-4" />
              Check API Health
            </Link>
          </div>
        </div>
      </main>

      <footer className="border-t border-slate-200/80 bg-slate-50/50 py-8 text-center text-xs text-slate-400">
        <div className="mx-auto max-w-6xl px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div>
            © {new Date().getFullYear()} ${toTitle(plan.projectName)}. All rights reserved.
          </div>
          <div className="flex items-center gap-1.5">
            <span>Generated with ${starterBranding.cliName} ${starterBranding.version}</span>
            <span className="text-slate-300">•</span>
            <span className="font-semibold text-slate-550">${starterBranding.releaseName}</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
`
  );
}

async function writeDashboardPage(plan: CreatePlan): Promise<void> {
  const hasPrisma = plan.modules.includes('prisma');
  const hasRedis = plan.modules.includes('redis');
  const hasDocker = plan.modules.includes('docker');
  const hasCI = plan.modules.includes('github-actions');

  await writeFileSafe(
    path.join(plan.targetPath, 'src/app/dashboard/page.tsx'),
    `'use client';

import { useState, useEffect } from 'react';
import { DashboardShell } from '@/components/dashboard/DashboardShell';
import { StatCard } from '@/components/dashboard/StatCard';
import { BarChart3, Zap, HardDrive, Database, Cpu, Activity, ShieldCheck, Box, Workflow } from 'lucide-react';

interface HealthData {
  ok: boolean;
  service: string;
  timestamp: string;
}

export default function DashboardPage() {
  const [health, setHealth] = useState<HealthData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/health')
      .then((res) => res.json())
      .then((data) => {
        setHealth(data);
        setLoading(false);
      })
      .catch(() => {
        setLoading(false);
      });
  }, []);

  const hasPrisma = ${hasPrisma};
  const hasRedis = ${hasRedis};
  const hasDocker = ${hasDocker};
  const hasCI = ${hasCI};

  return (
    <DashboardShell
      title="Product Dashboard"
      description="A clean interface showing product metrics, connected services, and quick links."
    >
      {/* Active Modules Badges */}
      <div className="mb-8 flex flex-wrap gap-2">
        <span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700 ring-1 ring-inset ring-slate-700/10">
          <Activity className="h-3.5 w-3.5" /> Core Engine
        </span>
        {hasPrisma && (
          <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700 ring-1 ring-inset ring-emerald-600/10">
            <Database className="h-3.5 w-3.5" /> PostgreSQL (Prisma)
          </span>
        )}
        {hasRedis && (
          <span className="inline-flex items-center gap-1.5 rounded-full bg-rose-50 px-3 py-1.5 text-xs font-semibold text-rose-700 ring-1 ring-inset ring-rose-600/10">
            <Cpu className="h-3.5 w-3.5" /> Redis Cache
          </span>
        )}
        {hasDocker && (
          <span className="inline-flex items-center gap-1.5 rounded-full bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-700 ring-1 ring-inset ring-blue-600/10">
            <Box className="h-3.5 w-3.5" /> Docker Container
          </span>
        )}
        {hasCI && (
          <span className="inline-flex items-center gap-1.5 rounded-full bg-purple-50 px-3 py-1.5 text-xs font-semibold text-purple-700 ring-1 ring-inset ring-purple-600/10">
            <Workflow className="h-3.5 w-3.5" /> GitHub Actions
          </span>
        )}
      </div>

      {/* Metrics Section */}
      <section className="grid gap-6 md:grid-cols-3">
        <StatCard label="Total Projects" value="12" change="+4% this week" icon={BarChart3} />
        <StatCard label="API Requests" value="1,240" change="99.9% uptime" icon={Zap} />
        <StatCard label="Memory Usage" value="42MB" change="Within limits" icon={HardDrive} />
      </section>

      <div className="mt-8 grid gap-8 md:grid-cols-3">
        {/* API Health Card */}
        <div className="md:col-span-1 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm flex flex-col justify-between hover:shadow-md transition duration-200">
          <div>
            <h3 className="font-bold text-slate-950">API Health Status</h3>
            <p className="mt-2 text-sm text-slate-500 leading-relaxed font-medium">
              Monitors the backend \`/api/health\` JSON endpoint.
            </p>
          </div>
          <div className="mt-6 pt-6 border-t border-slate-100 flex items-center justify-between">
            <span className="text-sm font-semibold text-slate-700">Status</span>
            {loading ? (
              <span className="text-xs text-slate-400 font-medium animate-pulse">Checking...</span>
            ) : health?.ok ? (
              <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700 ring-1 ring-inset ring-emerald-600/10">
                <ShieldCheck className="h-3.5 w-3.5 animate-pulse" /> Operational
              </span>
            ) : (
              <span className="inline-flex items-center gap-1.5 rounded-full bg-rose-50 px-2.5 py-1 text-xs font-semibold text-rose-700 ring-1 ring-inset ring-rose-600/10">
                <Activity className="h-3.5 w-3.5" /> Offline
              </span>
            )}
          </div>
        </div>

        {/* Next Steps / Workspace Card */}
        <div className="md:col-span-2 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm hover:shadow-md transition duration-200">
          <h3 className="font-bold text-slate-950">Getting Started</h3>
          <p className="mt-2 text-sm text-slate-500 leading-relaxed font-medium">
            Follow these simple steps to build out your product logic:
          </p>
          
          <ul className="mt-6 space-y-4 text-sm text-slate-750 font-medium">
            <li className="flex gap-3">
              <span className="h-5 w-5 rounded-full bg-indigo-50 flex items-center justify-center text-xs font-bold text-indigo-600 flex-shrink-0 mt-0.5">1</span>
              <span>
                <strong>Customize UI:</strong> Edit <code className="text-xs bg-slate-100 px-1.5 py-0.5 rounded font-mono text-indigo-650">src/app/dashboard/page.tsx</code> to structure your product dashboard features.
              </span>
            </li>
            <li className="flex gap-3">
              <span className="h-5 w-5 rounded-full bg-indigo-50 flex items-center justify-center text-xs font-bold text-indigo-600 flex-shrink-0 mt-0.5">2</span>
              <span>
                <strong>API Endpoints:</strong> View <code className="text-xs bg-slate-100 px-1.5 py-0.5 rounded font-mono text-indigo-650">src/app/api/health/route.ts</code> to see how server routes map to services.
              </span>
            </li>
            {hasPrisma && (
              <li className="flex gap-3">
                <span className="h-5 w-5 rounded-full bg-indigo-50 flex items-center justify-center text-xs font-bold text-indigo-600 flex-shrink-0 mt-0.5">3</span>
                <span>
                  <strong>Database Setup:</strong> Run <code className="text-xs bg-slate-100 px-1.5 py-0.5 rounded font-mono text-indigo-655">npm run db:push</code> to synchronize the schema.
                </span>
              </li>
            )}
          </ul>
        </div>
      </div>
    </DashboardShell>
  );
}
`
  );
}

async function writeDashboardComponents(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/components/dashboard/DashboardShell.tsx'),
    `import type { ReactNode } from 'react';
import Link from 'next/link';
import { Layers, Github } from 'lucide-react';

interface DashboardShellProps {
  title: string;
  description: string;
  children: ReactNode;
}

export function DashboardShell({
  title,
  description,
  children,
}: DashboardShellProps) {
  return (
    <div className="min-h-screen flex flex-col bg-slate-50/50">
      <header className="border-b border-slate-200/80 bg-white/80 backdrop-blur-md sticky top-0 z-50">
        <div className="mx-auto max-w-6xl px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-6">
            <Link href="/" className="flex items-center gap-2">
              <span className="h-6 w-6 rounded-lg bg-indigo-600 flex items-center justify-center text-xs font-bold text-white shadow-sm shadow-indigo-500/30">
                <Layers className="h-4.5 w-4.5" />
              </span>
              <span className="text-base font-bold tracking-tight text-slate-900">Workspace</span>
            </Link>
            <nav className="hidden sm:flex gap-4">
              <Link href="/dashboard" className="text-sm font-semibold text-slate-900">
                Dashboard
              </Link>
            </nav>
          </div>
          <div className="flex items-center gap-4">
            <a
              href="${starterBranding.githubUrl}"
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm font-medium text-slate-500 hover:text-slate-900 transition inline-flex items-center gap-1"
            >
              <Github className="h-4 w-4" />
              GitHub Docs
            </a>
          </div>
        </div>
      </header>

      <main className="flex-1 mx-auto w-full max-w-6xl px-6 py-10">
        <div className="mb-8">
          <h1 className="text-3xl font-extrabold tracking-tight text-slate-900">
            {title}
          </h1>
          <p className="mt-2 text-sm text-slate-500 font-medium">{description}</p>
        </div>

        {children}
      </main>

      <footer className="border-t border-slate-200 bg-white py-6 text-center text-xs text-slate-400">
        <div className="mx-auto max-w-6xl px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div>
            © {new Date().getFullYear()} Workspace. All rights reserved.
          </div>
          <div className="flex items-center gap-1.5">
            <span>Generated with ${starterBranding.cliName} ${starterBranding.version}</span>
            <span className="text-slate-300">•</span>
            <span className="font-semibold text-slate-550">${starterBranding.releaseName}</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
`
  );

  await writeFileSafe(
    path.join(plan.targetPath, 'src/components/dashboard/StatCard.tsx'),
    `import { LucideIcon } from 'lucide-react';

interface StatCardProps {
  label: string;
  value: string;
  change?: string;
  icon: LucideIcon;
}

export function StatCard({ label, value, change, icon: Icon }: StatCardProps) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm flex items-center justify-between hover:shadow-md transition duration-200">
      <div>
        <p className="text-sm font-semibold text-slate-500 uppercase tracking-wide">{label}</p>
        <p className="mt-2 text-3xl font-extrabold tracking-tight text-slate-900">{value}</p>
        {change && (
          <p className="mt-1.5 text-xs text-slate-400 font-semibold">{change}</p>
        )}
      </div>
      <span className="p-3.5 bg-slate-55 rounded-2xl border border-slate-100 text-indigo-600">
        <Icon className="h-6 w-6" />
      </span>
    </div>
  );
}
`
  );
}

async function writeHealthRoute(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/app/api/health/route.ts'),
    `export async function GET() {
  return Response.json({
    ok: true,
    service: '${plan.projectName}',
    blueprint: 'fullstack-product',
    timestamp: new Date().toISOString(),
  });
}
`
  );
}

async function writeServerFiles(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/server/actions/index.ts'),
    `export async function exampleAction() {
  return {
    ok: true,
    message: 'Server action placeholder',
  };
}
`
  );

  await writeFileSafe(
    path.join(plan.targetPath, 'src/server/services/productService.ts'),
    `export interface ProductSummary {
  name: string;
  blueprint: string;
}

export function getProductSummary(): ProductSummary {
  return {
    name: ${JSON.stringify(plan.projectName)},
    blueprint: 'fullstack-product',
  };
}
`
  );

  await writeFileSafe(
    path.join(plan.targetPath, 'src/server/services/index.ts'),
    `export { getProductSummary } from './productService.js';
export type { ProductSummary } from './productService.js';
`
  );
}

async function writeLibFiles(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/lib/env.ts'),
    `export const env = {
  databaseUrl: process.env.DATABASE_URL,
  redisUrl: process.env.REDIS_URL,
} as const;
`
  );

  await writeFileSafe(
    path.join(plan.targetPath, 'src/lib/utils.ts'),
    `export function formatAppName(value: string): string {
  return value
    .split(/[-_\\s]+/)
    .filter(Boolean)
    .map((part) => \`\${part.charAt(0).toUpperCase()}\${part.slice(1)}\`)
    .join(' ');
}
`
  );
}

async function writeTypesFile(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/types/product.ts'),
    `export type ProductBlueprint = 'saas' | 'dashboard' | 'custom';

export interface ProductConfig {
  name: string;
  blueprint: ProductBlueprint;
}
`
  );
}
