import path from 'node:path';
import type { CreatePlan } from '../types.js';
import { writeFileSafe } from '../utils/files.js';
import { toPascal, toTitle } from '../utils/strings.js';

export async function applyWebsitePlan(plan: CreatePlan): Promise<void> {
  if (plan.blueprint !== 'website') {
    throw new Error('applyWebsitePlan can only be used with website plans.');
  }

  await writeLayout(plan);
  await writeSiteConfig(plan);
  await writeNavbar(plan);
  await writeFooter(plan);

  if (plan.modules.includes('contact-form')) {
    await writeContactForm(plan);
  }

  if (plan.shape === 'one-page') {
    await writeOnePageWebsite(plan);
  }

  if (plan.shape === 'multi-page') {
    await writeMultiPageWebsite(plan);
  }

  if (plan.modules.includes('seo')) {
    await writeSeoFiles(plan);
  }
}

function getWebsiteSections(plan: CreatePlan): string[] {
  const sections =
    plan.sections.length > 0
      ? [...plan.sections]
      : ['hero', 'features', 'contact'];

  if (plan.modules.includes('contact-form') && !sections.includes('contact')) {
    sections.push('contact');
  }

  return sections;
}

function getWebsitePages(plan: CreatePlan): string[] {
  const pages =
    plan.pages.length > 0 ? [...plan.pages] : ['home', 'about', 'contact'];

  if (!pages.includes('home')) {
    pages.unshift('home');
  }

  if (plan.modules.includes('contact-form') && !pages.includes('contact')) {
    pages.push('contact');
  }

  return pages;
}

async function writeLayout(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/app/layout.tsx'),
    `import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: '${toTitle(plan.projectName)}',
  description: 'Generated by ts-cli-tool',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
  );
}

async function writeSiteConfig(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/lib/site-config.ts'),
    `export const siteConfig = {
  name: '${toTitle(plan.projectName)}',
  description: 'Generated website starter.',
  url: 'https://example.com',
} as const;
`
  );
}

async function writeNavbar(plan: CreatePlan): Promise<void> {
  const links =
    plan.shape === 'one-page'
      ? getWebsiteSections(plan)
          .map(
            (section) =>
              `          <a href="#${section}" className="transition hover:text-slate-950">${toTitle(
                section
              )}</a>`
          )
          .join('\n')
      : getWebsitePages(plan)
          .map((page) => {
            const href = page === 'home' ? '/' : `/${page}`;

            return `          <Link href="${href}" className="transition hover:text-slate-950">${toTitle(
              page
            )}</Link>`;
          })
          .join('\n');

  const importLink =
    plan.shape === 'multi-page' ? `import Link from 'next/link';\n` : '';

  await writeFileSafe(
    path.join(plan.targetPath, 'src/components/layout/Navbar.tsx'),
    `${importLink}import { siteConfig } from '@/lib/site-config';

export function Navbar() {
  return (
    <header className="border-b border-slate-200 bg-white">
      <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
        <div className="text-sm font-semibold tracking-tight text-slate-950">
          {siteConfig.name}
        </div>

        <div className="flex gap-5 text-sm text-slate-600">
${links}
        </div>
      </nav>
    </header>
  );
}
`
  );
}

async function writeFooter(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/components/layout/Footer.tsx'),
    `import { siteConfig } from '@/lib/site-config';

export function Footer() {
  return (
    <footer className="border-t border-slate-200 px-6 py-8 text-center text-sm text-slate-600">
      © {new Date().getFullYear()} {siteConfig.name}. All rights reserved.
    </footer>
  );
}
`
  );
}

async function writeOnePageWebsite(plan: CreatePlan): Promise<void> {
  const sections = getWebsiteSections(plan);

  for (const section of sections) {
    await writeSectionComponent(plan, section);
  }

  const imports = sections
    .map((section) => {
      const componentName = `${toPascal(section)}Section`;

      return `import { ${componentName} } from '@/components/sections/${componentName}';`;
    })
    .join('\n');

  const renderedSections = sections
    .map((section) => {
      const componentName = `${toPascal(section)}Section`;

      return `        <${componentName} />`;
    })
    .join('\n');

  await writeFileSafe(
    path.join(plan.targetPath, 'src/app/page.tsx'),
    `${imports}
import { Footer } from '@/components/layout/Footer';
import { Navbar } from '@/components/layout/Navbar';

export default function HomePage() {
  return (
    <>
      <Navbar />
      <main>
${renderedSections}
      </main>
      <Footer />
    </>
  );
}
`
  );
}

async function writeSectionComponent(
  plan: CreatePlan,
  section: string
): Promise<void> {
  const componentName = `${toPascal(section)}Section`;
  const shouldRenderContactForm =
    section === 'contact' && plan.modules.includes('contact-form');

  const contactImport = shouldRenderContactForm
    ? `import { ContactForm } from '@/components/forms/ContactForm';\n\n`
    : '';

  const contactForm = shouldRenderContactForm
    ? `
      <div className="mt-8 max-w-xl">
        <ContactForm />
      </div>`
    : '';

  await writeFileSafe(
    path.join(plan.targetPath, `src/components/sections/${componentName}.tsx`),
    `${contactImport}export function ${componentName}() {
  return (
    <section id="${section}" className="mx-auto max-w-6xl px-6 py-20">
      <p className="mb-3 text-sm font-medium uppercase tracking-wide text-slate-500">
        ${toTitle(section)}
      </p>
      <h2 className="max-w-3xl text-3xl font-bold tracking-tight text-slate-950">
        ${toTitle(section)} section
      </h2>
      <p className="mt-4 max-w-2xl text-slate-600">
        Replace this starter content with your real ${section} content.
      </p>${contactForm}
    </section>
  );
}
`
  );
}

async function writeMultiPageWebsite(plan: CreatePlan): Promise<void> {
  const pages = getWebsitePages(plan);

  for (const page of pages) {
    await writeWebsitePage(plan, page);
  }
}

async function writeWebsitePage(plan: CreatePlan, page: string): Promise<void> {
  const isHome = page === 'home';
  const isContactPage = page === 'contact';
  const shouldRenderContactForm =
    isContactPage && plan.modules.includes('contact-form');

  const pagePath = isHome
    ? path.join(plan.targetPath, 'src/app/page.tsx')
    : path.join(plan.targetPath, `src/app/${page}/page.tsx`);

  const componentName = isHome ? 'HomePage' : `${toPascal(page)}Page`;
  const heading = isHome ? toTitle(plan.projectName) : toTitle(page);

  const contactImport = shouldRenderContactForm
    ? `import { ContactForm } from '@/components/forms/ContactForm';\n`
    : '';

  const contactForm = shouldRenderContactForm
    ? `
        <div className="mt-8 max-w-xl">
          <ContactForm />
        </div>`
    : '';

  await writeFileSafe(
    pagePath,
    `${contactImport}import { Footer } from '@/components/layout/Footer';
import { Navbar } from '@/components/layout/Navbar';

export default function ${componentName}() {
  return (
    <>
      <Navbar />
      <main className="mx-auto max-w-6xl px-6 py-20">
        <p className="mb-3 text-sm font-medium uppercase tracking-wide text-slate-500">
          ${isHome ? 'Home' : toTitle(page)}
        </p>
        <h1 className="max-w-3xl text-4xl font-bold tracking-tight text-slate-950">
          ${heading}
        </h1>
        <p className="mt-4 max-w-2xl text-slate-600">
          Replace this starter content with your real ${
            isHome ? 'home page' : `${page} page`
          } content.
        </p>${contactForm}
      </main>
      <Footer />
    </>
  );
}
`
  );
}

async function writeContactForm(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/components/forms/ContactForm.tsx'),
    `export function ContactForm() {
  return (
    <form className="space-y-4 rounded-xl border border-slate-200 p-6">
      <div>
        <label className="mb-2 block text-sm font-medium text-slate-700" htmlFor="name">
          Name
        </label>
        <input
          id="name"
          className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-slate-950"
          placeholder="Your name"
          type="text"
        />
      </div>

      <div>
        <label className="mb-2 block text-sm font-medium text-slate-700" htmlFor="email">
          Email
        </label>
        <input
          id="email"
          className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-slate-950"
          placeholder="you@example.com"
          type="email"
        />
      </div>

      <div>
        <label className="mb-2 block text-sm font-medium text-slate-700" htmlFor="message">
          Message
        </label>
        <textarea
          id="message"
          className="min-h-32 w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-slate-950"
          placeholder="Tell us about your project..."
        />
      </div>

      <button
        className="rounded-md bg-slate-950 px-5 py-2.5 text-sm font-medium text-white"
        type="submit"
      >
        Send message
      </button>
    </form>
  );
}
`
  );
}

async function writeSeoFiles(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/app/robots.ts'),
    `import type { MetadataRoute } from 'next';
import { siteConfig } from '@/lib/site-config';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
    },
    sitemap: \`\${siteConfig.url}/sitemap.xml\`,
  };
}
`
  );

  await writeFileSafe(
    path.join(plan.targetPath, 'src/app/sitemap.ts'),
    `import type { MetadataRoute } from 'next';
import { siteConfig } from '@/lib/site-config';

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: siteConfig.url,
      lastModified: new Date(),
    },
  ];
}
`
  );
}
