import path from 'node:path';
import type { CreatePlan } from '../types.js';
import { readJsonFile, writeFileSafe, writeJsonFile } from '../utils/files.js';

interface GeneratedPackageJson {
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

export async function applyFeatureModules(plan: CreatePlan): Promise<void> {
  await updateGeneratedPackageJson(plan);

  if (plan.modules.includes('prisma')) {
    await writePrismaModule(plan);
  }

  if (plan.modules.includes('redis')) {
    await writeRedisModule(plan);
  }

  if (shouldWriteEnvExample(plan)) {
    await writeEnvExample(plan);
  }

  if (plan.modules.includes('docker')) {
    await writeDockerFiles(plan);
  }

  if (plan.modules.includes('github-actions')) {
    await writeGithubActionsWorkflow(plan);
  }
}

async function updateGeneratedPackageJson(plan: CreatePlan): Promise<void> {
  const packageJsonPath = path.join(plan.targetPath, 'package.json');
  const packageJson = await readJsonFile<GeneratedPackageJson>(packageJsonPath);

  const scripts = {
    ...(packageJson.scripts ?? {}),
  };

  const dependencies = {
    ...(packageJson.dependencies ?? {}),
  };

  const devDependencies = {
    ...(packageJson.devDependencies ?? {}),
  };

  scripts.typecheck = 'tsc --noEmit';

  // Add lucide-react for premium icons across all starter projects
  dependencies['lucide-react'] = '^0.400.0';

  if (plan.modules.includes('prisma')) {
    dependencies['@prisma/client'] = '^6.0.0';
    devDependencies.prisma = '^6.0.0';

    scripts.db = 'prisma studio';
    scripts['db:push'] = 'prisma db push';
    scripts['db:generate'] = 'prisma generate';
  }

  if (plan.modules.includes('redis')) {
    dependencies.ioredis = '^5.0.0';
  }

  packageJson.scripts = scripts;
  packageJson.dependencies = dependencies;
  packageJson.devDependencies = devDependencies;

  await writeJsonFile(packageJsonPath, packageJson);
}

async function writePrismaModule(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'prisma/schema.prisma'),
    `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
`
  );

  await writeFileSafe(
    path.join(plan.targetPath, 'src/lib/db.ts'),
    `import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis as unknown as {
  prisma?: PrismaClient;
};

export const db = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = db;
}
`
  );
}

async function writeRedisModule(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'src/lib/redis.ts'),
    `import Redis from 'ioredis';

const globalForRedis = globalThis as unknown as {
  redis?: Redis;
};

export const redis =
  globalForRedis.redis ??
  new Redis(process.env.REDIS_URL ?? 'redis://localhost:6379');

if (process.env.NODE_ENV !== 'production') {
  globalForRedis.redis = redis;
}
`
  );
}

function shouldWriteEnvExample(plan: CreatePlan): boolean {
  return (
    plan.modules.includes('env-example') ||
    plan.modules.includes('postgresql') ||
    plan.modules.includes('redis') ||
    plan.modules.includes('ai-sdk')
  );
}

async function writeEnvExample(plan: CreatePlan): Promise<void> {
  const lines = ['# Generated by ts-cli-tool'];

  if (plan.modules.includes('postgresql')) {
    lines.push(
      'DATABASE_URL="postgresql://postgres:postgres@localhost:5432/app_db?schema=public"'
    );
  }

  if (plan.modules.includes('redis')) {
    lines.push('REDIS_URL="redis://localhost:6379"');
  }

  if (plan.modules.includes('ai-sdk')) {
    lines.push('AI_API_KEY="your-ai-provider-api-key"');
    lines.push('AI_MODEL="your-model-name"');
  }

  await writeFileSafe(
    path.join(plan.targetPath, '.env.example'),
    `${lines.join('\n')}\n`
  );
}

async function writeDockerFiles(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, 'Dockerfile'),
    `FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm install

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app ./
EXPOSE 3000
CMD ["npm", "start"]
`
  );

  if (!plan.modules.includes('postgresql') && !plan.modules.includes('redis')) {
    return;
  }

  const services: string[] = [];

  if (plan.modules.includes('postgresql')) {
    services.push(`  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data`);
  }

  if (plan.modules.includes('redis')) {
    services.push(`  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"`);
  }

  const volumes = plan.modules.includes('postgresql')
    ? `
volumes:
  postgres_data:
`
    : '';

  await writeFileSafe(
    path.join(plan.targetPath, 'docker-compose.yml'),
    `services:
${services.join('\n\n')}
${volumes}`
  );
}

async function writeGithubActionsWorkflow(plan: CreatePlan): Promise<void> {
  await writeFileSafe(
    path.join(plan.targetPath, '.github/workflows/ci.yml'),
    `name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Build
        run: npm run build --if-present
`
  );
}
