import path from 'node:path';
import type {
  BasicScaffoldOptions,
  EslintConfig,
  PackageJson,
} from '../types.js';
import { writeJson } from '../utils/writeJson.js';
import { writeFileSafe, ensureDir } from '../utils/files.js';

export async function generateBasicProject(
  options: BasicScaffoldOptions
): Promise<void> {
  const {
    projectName,
    targetPath,
    useTypeScript,
    includeLint,
    includeJest,
    includeDocker,
  } = options;

  await ensureDir(targetPath);

  const packageJson: PackageJson = {
    name: projectName,
    version: '1.0.0',
    description: 'Generated by ts-cli-tool',
    main: useTypeScript ? 'src/index.ts' : 'src/index.js',
    scripts: {
      start: useTypeScript ? 'tsx src/index.ts' : 'node src/index.js',
    },
    devDependencies: {},
  };

  if (useTypeScript) {
    packageJson.devDependencies.typescript = '^5.0.0';
    packageJson.devDependencies.tsx = '^4.0.0';
    packageJson.devDependencies['@types/node'] = '^20.0.0';
  }

  if (includeLint) {
    packageJson.devDependencies.eslint = '^8.0.0';
    packageJson.scripts.lint = 'eslint src/**/*';

    const eslintConfig: EslintConfig = {
      env: { node: true },
      extends: ['eslint:recommended'],
    };

    if (useTypeScript) {
      packageJson.devDependencies['@typescript-eslint/parser'] = '^7.0.0';
      packageJson.devDependencies['@typescript-eslint/eslint-plugin'] =
        '^7.0.0';

      eslintConfig.parser = '@typescript-eslint/parser';
      eslintConfig.extends.push('plugin:@typescript-eslint/recommended');
    }

    await writeJson(path.join(targetPath, '.eslintrc.json'), eslintConfig);
  }

  if (includeJest) {
    packageJson.devDependencies.jest = '^29.0.0';
    packageJson.scripts.test = 'jest';

    let jestConfig = `module.exports = { testEnvironment: 'node' };\n`;

    if (useTypeScript) {
      packageJson.devDependencies['ts-jest'] = '^29.0.0';
      packageJson.devDependencies['@types/jest'] = '^29.0.0';

      jestConfig = `module.exports = { preset: 'ts-jest', testEnvironment: 'node' };\n`;
    }

    await writeFileSafe(path.join(targetPath, 'jest.config.js'), jestConfig);
  }

  await writeJson(path.join(targetPath, 'package.json'), packageJson);

  if (includeDocker) {
    const dockerfileContent = `FROM node:18-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
CMD ["npm", "start"]
`;

    await writeFileSafe(path.join(targetPath, 'Dockerfile'), dockerfileContent);
  }

  await ensureDir(path.join(targetPath, 'src'));

  const fileExt = useTypeScript ? 'ts' : 'js';

  const fileContent = `console.log('🚀 Successfully running ${projectName}!');\n`;

  await writeFileSafe(
    path.join(targetPath, `src/index.${fileExt}`),
    fileContent
  );
}
