import path from 'node:path';
import type { CreatePlan } from '../types.js';
import { writeFileSafe } from '../utils/files.js';
import { toTitle } from '../utils/strings.js';

export async function writeGeneratedReadme(plan: CreatePlan): Promise<void> {
  const modules =
    plan.modules.length > 0
      ? plan.modules.map((module) => `- ${module}`).join('\n')
      : '- none';

  const envInstructions = plan.modules.includes('env-example')
    ? `

## Environment

Create your local environment file:

\`\`\`bash
cp .env.example .env
\`\`\`

On Windows PowerShell:

\`\`\`powershell
Copy-Item .env.example .env
\`\`\`
`
    : '';

  const databaseInstructions = plan.modules.includes('prisma')
    ? `

## Database

After configuring your \`.env\` file, push the Prisma schema:

\`\`\`bash
npm run db:push
\`\`\`

Open Prisma Studio:

\`\`\`bash
npm run db
\`\`\`
`
    : '';

  const dockerInstructions = plan.modules.includes('docker')
    ? `

## Docker

Build and run the project with Docker when needed.

If \`docker-compose.yml\` was generated, start services with:

\`\`\`bash
docker compose up -d
\`\`\`
`
    : '';

  await writeFileSafe(
    path.join(plan.targetPath, 'README.md'),
    `# ${toTitle(plan.projectName)}

Generated by \`ts-cli-tool\`.

## Blueprint

\`${plan.blueprint}\`

## Shape

\`${plan.shape}\`

## Modules

${modules}

## Getting started

Install dependencies:

\`\`\`bash
npm install
\`\`\`

Start the development server:

\`\`\`bash
npm run dev
\`\`\`
${envInstructions}${databaseInstructions}${dockerInstructions}
`
  );
}
