#!/usr/bin/env node

import { Command } from 'commander';
import { input, confirm } from '@inquirer/prompts';
import fs from 'fs/promises';
import path from 'path';

// Fix #5: Define a strict interface to remove the 'any' type
interface PackageJson {
  name: string;
  version: string;
  description: string;
  main: string;
  scripts: Record<string, string>;
  devDependencies: Record<string, string>;
}

const program = new Command();

program
  .name('my-cli')
  .description('A powerful, strongly-typed CLI tool')
  .version('1.0.0');

program
  .command('greet')
  .description('Greets the user by name')
  .argument('<name>', 'The name of the person to greet')
  .action((name: string) => {
    console.log(`🚀 Hello, ${name}! Your TypeScript CLI is officially alive.`);
  });

program
  .command('create')
  .description('Scaffolds a new project directory structure')
  .action(async () => {
    console.log("\nLet's build a new project! 🛠️\n");

    const projectName = await input({
      message: 'What is the name of your project?',
      default: 'my-new-app',
      // Fix #8: Add project name validation
      validate: (value) => {
        if (!/^[a-z0-9-_]+$/i.test(value)) {
          return 'Project name can only contain letters, numbers, hyphens, and underscores.';
        }
        return true;
      },
    });

    const useTypeScript = await confirm({
      message: 'Would you like to initialize this as a TypeScript project?',
      default: true,
    });

    const includeLint = await confirm({
      message: 'Would you like to add ESLint for code quality?',
      default: true,
    });

    const includeJest = await confirm({
      message: 'Would you like to add Jest for automated testing?',
      default: true,
    });

    const includeDocker = await confirm({
      message: 'Would you like to generate a Dockerfile for containerization?',
      default: false,
    });

    const targetPath = path.join(process.cwd(), projectName);

    try {
      console.log(`\nScaffolding project in ${targetPath}...`);
      await fs.mkdir(targetPath, { recursive: true });

      // Utilizing our new PackageJson interface
      const packageJson: PackageJson = {
        name: projectName,
        version: '1.0.0',
        description: 'Generated by ts-cli-tool',
        main: useTypeScript ? 'src/index.ts' : 'src/index.js',
        scripts: {
          start: useTypeScript ? 'tsx src/index.ts' : 'node src/index.js',
        },
        devDependencies: {},
      };

      if (useTypeScript) {
        packageJson.devDependencies['typescript'] = '^5.0.0';
        packageJson.devDependencies['tsx'] = '^4.0.0';
        packageJson.devDependencies['@types/node'] = '^20.0.0';
      }

      // Fix #7: Properly configure ESLint for TypeScript
      if (includeLint) {
        packageJson.devDependencies['eslint'] = '^8.0.0';
        packageJson.scripts['lint'] = 'eslint src/**/*';

        const eslintConfig: any = {
          env: { node: true },
          extends: ['eslint:recommended'],
        };

        if (useTypeScript) {
          packageJson.devDependencies['@typescript-eslint/parser'] = '^7.0.0';
          packageJson.devDependencies['@typescript-eslint/eslint-plugin'] =
            '^7.0.0';
          eslintConfig.parser = '@typescript-eslint/parser';
          eslintConfig.extends.push('plugin:@typescript-eslint/recommended');
        }

        await fs.writeFile(
          path.join(targetPath, '.eslintrc.json'),
          JSON.stringify(eslintConfig, null, 2)
        );
      }

      // Fix #6: Correct the Jest preset logic
      if (includeJest) {
        packageJson.devDependencies['jest'] = '^29.0.0';
        packageJson.scripts['test'] = 'jest';

        let jestConfig = `export default { testEnvironment: 'node' };\n`;

        if (useTypeScript) {
          packageJson.devDependencies['ts-jest'] = '^29.0.0';
          packageJson.devDependencies['@types/jest'] = '^29.0.0';
          jestConfig = `export default { preset: 'ts-jest', testEnvironment: 'node' };\n`;
        }

        // Write as jest.config.js (using ESM export)
        await fs.writeFile(path.join(targetPath, 'jest.config.js'), jestConfig);
      }

      await fs.writeFile(
        path.join(targetPath, 'package.json'),
        JSON.stringify(packageJson, null, 2)
      );

      if (includeDocker) {
        const dockerfileContent = `FROM node:18-alpine\nWORKDIR /usr/src/app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nCMD ["npm", "start"]\n`;
        await fs.writeFile(
          path.join(targetPath, 'Dockerfile'),
          dockerfileContent
        );
      }

      await fs.mkdir(path.join(targetPath, 'src'), { recursive: true });
      const fileExt = useTypeScript ? 'ts' : 'js';
      const fileContent = `console.log('🚀 Successfully running ${projectName}!');\n`;
      await fs.writeFile(
        path.join(targetPath, `src/index.${fileExt}`),
        fileContent
      );

      console.log('\n✅ Enterprise project successfully scaffolded!');
      console.log(`\nNext steps:`);
      console.log(`  cd ${projectName}`);
      console.log(`  npm install\n`);
    } catch (error) {
      console.error('\n❌ Failed to scaffold the project:', error);
    }
  });

program.parse();
